name: Snyk Analysis
env:
  DOTNET_VERSION: '8.x'                     # la versión de .NET
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: snyk/actions/setup@master
      - name: Configurando la versión de NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}  
      - name: Snyk monitor
        run: snyk code test --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}          
    #- uses: actions/checkout@master  
    #- name: Run Snyk to check for vulnerabilities
    #  uses: snyk/actions/dotnet@master
    #   #continue-on-error: true # To make sure that SARIF upload gets called
    #  env:
    #    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    #  with:
    #    args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
